[
  {
    id: "section-1",
    section: "Location",
    fields: [
      {
        type: "select",
        id: "field-1740112986647",
        label: "Select District",
        name: "District",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
          {
            value: 1,
            label: "Anantnag",
          },
          {
            value: 2,
            label: "Budgam",
          },
          {
            value: 3,
            label: "Baramulla",
          },
          {
            value: 4,
            label: "Doda",
          },
          {
            value: 5,
            label: "Jammu",
          },
          {
            value: 7,
            label: "Kathua",
          },
          {
            value: 8,
            label: "Kupwara",
          },
          {
            value: 10,
            label: "Poonch",
          },
          {
            value: 11,
            label: "Pulwama",
          },
          {
            value: 12,
            label: "Rajouri",
          },
          {
            value: 13,
            label: "Srinagar",
          },
          {
            value: 14,
            label: "Udhampur",
          },
          {
            value: 620,
            label: "Kishtwar",
          },
          {
            value: 621,
            label: "Ramban",
          },
          {
            value: 622,
            label: "Kulgam",
          },
          {
            value: 623,
            label: "Bandipora",
          },
          {
            value: 624,
            label: "Samba",
          },
          {
            value: 625,
            label: "Shopian",
          },
          {
            value: 626,
            label: "Ganderbal",
          },
          {
            value: 627,
            label: "Reasi",
          },
        ],
        span: 12,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-1",
        optionsType: "independent",
      },
      {
        type: "select",
        id: "field-1740113022969",
        label: "Select Tehsil Social Welfare Office (TSWO)",
        name: "Tehsil",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
        ],
        span: 12,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-1",
        optionsType: "independent",
      },
    ],
  },
  {
    id: "section-2",
    section: "Applicant Details",
    fields: [
      {
        type: "text",
        id: "field-1740113295080",
        label: "Applicant Name",
        name: "ApplicantName",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
      },
      {
        type: "file",
        id: "field-1740113323210",
        label: "Applicant Image",
        name: "ApplicantImage",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "validateFile"],
        transformationFunctions: [],
        additionalFields: {},
        accept: ".jpg,.png,.jpeg",
        sectionId: "section-2",
      },
      {
        type: "date",
        id: "field-1740113369706",
        label: "Date of Birth",
        name: "DateOfBirth",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "isAgeGreaterThan"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
      },
      {
        type: "text",
        id: "field-1740113510302",
        label: "Mobile Number",
        name: "MobileNumber",
        minLength: 5,
        maxLength: 10,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyDigits", "specificLength"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
      },
      {
        type: "email",
        id: "field-1740113552892",
        label: "Email",
        name: "Email",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "isEmailValid"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
      },
      {
        type: "select",
        id: "field-1740214101402",
        label: "Relation",
        name: "Relation",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Father",
            label: "Father",
          },
          {
            value: "Husband",
            label: "Husband",
          },
          {
            value: "Guardian",
            label: "Guardian",
          },
        ],
        span: 6,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
        optionsType: "independent",
      },
      {
        type: "text",
        id: "field-1740214191466",
        label: "Relation Name",
        name: "RelationName",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-2",
      },
    ],
  },
  {
    id: "section-3",
    section: "Present Address Details",
    fields: [
      {
        type: "text",
        id: "field-1740113618417",
        label: "Address",
        name: "PresentAddress",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 12,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "select",
        id: "field-1740113676245",
        label: "District",
        name: "PresentDistrict",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
          {
            value: 1,
            label: "Anantnag",
          },
          {
            value: 2,
            label: "Budgam",
          },
          {
            value: 3,
            label: "Baramulla",
          },
          {
            value: 4,
            label: "Doda",
          },
          {
            value: 5,
            label: "Jammu",
          },
          {
            value: 7,
            label: "Kathua",
          },
          {
            value: 8,
            label: "Kupwara",
          },
          {
            value: 10,
            label: "Poonch",
          },
          {
            value: 11,
            label: "Pulwama",
          },
          {
            value: 12,
            label: "Rajouri",
          },
          {
            value: 13,
            label: "Srinagar",
          },
          {
            value: 14,
            label: "Udhampur",
          },
          {
            value: 620,
            label: "Kishtwar",
          },
          {
            value: 621,
            label: "Ramban",
          },
          {
            value: 622,
            label: "Kulgam",
          },
          {
            value: 623,
            label: "Bandipora",
          },
          {
            value: 624,
            label: "Samba",
          },
          {
            value: 625,
            label: "Shopian",
          },
          {
            value: 626,
            label: "Ganderbal",
          },
          {
            value: 627,
            label: "Reasi",
          },
        ],
        span: 6,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
        optionsType: "independent",
      },
      {
        type: "select",
        id: "field-1740113724788",
        label: "Tehsil",
        name: "PresentTehsil",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
        ],
        span: 6,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "text",
        id: "field-1740113751965",
        label: "Block",
        name: "PresentBlock",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "text",
        id: "field-1740113773920",
        label: "Ward",
        name: "PresentWard",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "text",
        id: "field-1740113790511",
        label: "Village",
        name: "PresentVillage",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "text",
        id: "field-1740113809543",
        label: "Pincode",
        name: "PresentPincode",
        minLength: 5,
        maxLength: 6,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyDigits", "specificLength"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
    ],
  },
  {
    id: "section-4",
    section: "Permanent Address Details",
    fields: [
      {
        type: "text",
        id: "field-1740113835649-ynebn6g",
        label: "Address",
        name: "PermanentAddress",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 12,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-3",
      },
      {
        type: "select",
        id: "field-1740113835650-1u1dysc",
        label: "District",
        name: "PermanentDistrict",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
          {
            value: 1,
            label: "Anantnag",
          },
          {
            value: 2,
            label: "Budgam",
          },
          {
            value: 3,
            label: "Baramulla",
          },
          {
            value: 4,
            label: "Doda",
          },
          {
            value: 5,
            label: "Jammu",
          },
          {
            value: 7,
            label: "Kathua",
          },
          {
            value: 8,
            label: "Kupwara",
          },
          {
            value: 10,
            label: "Poonch",
          },
          {
            value: 11,
            label: "Pulwama",
          },
          {
            value: 12,
            label: "Rajouri",
          },
          {
            value: 13,
            label: "Srinagar",
          },
          {
            value: 14,
            label: "Udhampur",
          },
          {
            value: 620,
            label: "Kishtwar",
          },
          {
            value: 621,
            label: "Ramban",
          },
          {
            value: 622,
            label: "Kulgam",
          },
          {
            value: 623,
            label: "Bandipora",
          },
          {
            value: 624,
            label: "Samba",
          },
          {
            value: 625,
            label: "Shopian",
          },
          {
            value: 626,
            label: "Ganderbal",
          },
          {
            value: 627,
            label: "Reasi",
          },
        ],
        span: 6,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
        optionsType: "independent",
      },
      {
        type: "select",
        id: "field-1740113835650-sg4eh7t",
        label: "Tehsil",
        name: "PermanentTehsil",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
        ],
        span: 6,
        validationFunctions: ["notEmpty"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
      },
      {
        type: "text",
        id: "field-1740113835650-5ik8q7z",
        label: "Block",
        name: "PermanentBlock",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
      },
      {
        type: "text",
        id: "field-1740113835650-u8jdlbr",
        label: "Ward",
        name: "PermanentWard",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
      },
      {
        type: "text",
        id: "field-1740113835650-9dnwkdb",
        label: "Village",
        name: "PermanentVillage",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
      },
      {
        type: "text",
        id: "field-1740113835650-ozlqf46",
        label: "Pincode",
        name: "PermanentPincode",
        minLength: 5,
        maxLength: 6,
        options: [],
        span: 6,
        validationFunctions: ["notEmpty", "onlyDigits", "specificLength"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-4",
      },
    ],
  },
  {
    id: "section-5",
    section: "Bank Details",
    fields: [
      {
        type: "select",
        id: "field-1740199601220",
        label: "Select Bank",
        name: "BankName",
        minLength: 5,
        maxLength: 50,
        options: [
          {
            value: "Please Select",
            label: "Please Select",
          },
          {
            value: "THE JAMMU AND KASHMIR BANK",
            label: "THE JAMMU AND KASHMIR BANK",
          },
          {
            value: "PUNJAB BANK",
            label: "PUNJAB BANK",
          },
          {
            value: "JK GRAMEEN BANK",
            label: "JK GRAMEEN BANK",
          },
        ],
        span: 12,
        validationFunctions: [],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-5",
        optionsType: "independent",
      },
      {
        type: "text",
        id: "field-1740199834738",
        label: "Branch Name",
        name: "BranchName",
        minLength: 5,
        maxLength: 50,
        options: [],
        span: 12,
        validationFunctions: ["notEmpty", "onlyAlphabets"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-5",
      },
      {
        type: "text",
        id: "field-1740199859569",
        label: "IFSC Code",
        name: "IfscCode",
        minLength: 5,
        maxLength: 11,
        options: [],
        span: 12,
        validationFunctions: ["notEmpty", "specificLength"],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-5",
      },
      {
        type: "text",
        id: "field-1740199893324",
        label: "Account Number",
        name: "AccountNumber",
        minLength: 5,
        maxLength: 16,
        options: [],
        span: 12,
        validationFunctions: [
          "notEmpty",
          "onlyDigits",
          "specificLength",
          "duplicateAccountNumber",
        ],
        transformationFunctions: [],
        additionalFields: {},
        accept: "",
        sectionId: "section-5",
      },
    ],
  },
  {
    id: "section-6",
    section: "Documents",
    fields: [],
  },
];
